### ISSUE TITLE
Checklist Running on March III

### ISSUE THREAD

**Issue by TimBuckers** [project-march/march-iv#160]
## Hardware Interface

- [x] Encoder factor implementation #155
- [x] Implement actuate #153

### Optional
- [ ] Refactor PDO Mapping #154
- [ ] Implement PDB Slave. #153

## Test Joint
- [x] Connect hardware interface read to robot hardware interface.
- [x] Validate ros_control calculates correct commands.
- [x] Connect hardware interface to robot hardware interface.
- [x] Visualize in Rviz.
- [x] Send command to ros_controller.

## March III 
- [x] Read all encoders with hardware_interface #149
- [x] Publish encoders to RVIZ #149
- [x] Confirm that encoder factor still works. #149
- [x] Actuate using hardware_interface. #150
